version: "3.8"
services: 
    net_est:
        image: "network-uncertainty"
        build: 
            context: .
            dockerfile: net_est.dockerfile
        working_dir: /code/net_est
        shm_size: '1gb'
        volumes: 
          - "${DEV_CODE}:/code"
          - "${DEV_DATA}:/data"
          - "${DEV_IMAGE}:/images"
          - "${DEV_CONFIG}:/configs"
          - "${DEV_RESULTS}:/results"
        environment:
            NVIDIA_VISIBLE_DEVICES: 0 # or "all" or "0" or "0,1" etc.
            TF_FORCE_GPU_ALLOW_GROWTH: 'true' 
        command: /bin/sh -c "while sleep 1000; do :; done"