noisy_sin:
  networkType: 'feedforward'
  input_shape: 1
  output_shape: 1
  hidden_layers: 2
  nodes: [50, 50]
  activation: 'relu'
  loss: 'mse'
  kernel_init: 'glorot_uniform'
  kernel_reg: null
  optimizer: 'RMSProp'
  epochs: 50
  lr: 0.1
  n_models: 50
  batch_size: 64
  training_iterations: 2


