noisy_sin:
  networkType: 'feedforward'
  input_shape: 1
  output_shape: 1
  hidden_layers: 5
  nodes: [50, 50, 50, 50, 50]
  activation: 'relu'
  loss: 'mse'
  kernel_init: 'glorot_uniform'
  kernel_reg: null
  optimizer: 'RMSProp'
  epochs: 500
  lr: 0.1
  n_models: 5
  n_samples: 5000
  batch_size: 1024
  patience: 5
  dropout_rate: 0.1
  training_iterations: 2
  lr_reduce_factor: 0.1
  cooldown: 2
  min_lr: 1.0E-10


